name: linux

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        distro:
          #          - alpine
            #          - archlinux
          - debian
            #          - fedora
            #          - opensuse
            #    - gentoo
        cpp_std: [c++20]

    runs-on: ubuntu-latest
    container:
      image: alexays/waybar:${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: meson -Dman-pages=enabled -Dcpp_std=${{matrix.cpp_std}} build
      - name: build
        run: ninja -C build
      - name: test
        run: make test

      - name: Zip the Build
        run: |
          tar -czf release.tar.gz ./build/

      - uses: actions/upload-artifact@v4
        with:
        name: artifact
        path: release.tar.gz
        compression-level: 9 # maximum compression
